//! Decode JC3's bias-encoded velocity buffer into an unbiased motion-vector buffer for FSR.
//!
//! JC3's `m_VelocityBufferTexture` stores `clamp((curUV-prevUV)*8, -1, 1)*0.5 + 0.5` (8-bit, Y-down
//! UV; RE'd from the velocity-write shader -- see `docs/mod/fsr.md`). FSR's `motionVectorScale` is a pure
//! multiply and cannot undo the `+0.5` bias, so this runs a compute shader that decodes
//! `(stored-0.5)*0.25` into an `R16G16_FLOAT` buffer FSR consumes, applying a runtime sign/axis
//! convention. The compiled shader is committed (`velocity_decode.dxbc`, regenerated by
//! `shadergen`), so there is no runtime shader compiler.
//!
//! The same pass also corrects the vectors for stereo: the engine encodes `curUV - prevUV` against a
//! single sim-side *center* previous view-projection while each eye rasterizes with its own, so every
//! static pixel carries a spurious depth-dependent parallax vector of opposite sign per eye, and FSR
//! mis-reprojects each eye's temporal history (the per-eye shadow-edge flicker of issue #10). Given
//! the two clip-to-previous-clip reprojection matrices from [`crate::stereo::VpHistory`], the shader
//! reconstructs each pixel from the raster depth and re-anchors its vector at the eye's own previous
//! pose; see `velocity_decode.hlsl` for the math.

use jc3gi::graphics_engine::{device::Device, texture::Texture};
use windows::{
    Win32::Graphics::{
        Direct3D::D3D_SRV_DIMENSION_TEXTURE2D,
        Direct3D11::{
            D3D11_BIND_CONSTANT_BUFFER, D3D11_BIND_SHADER_RESOURCE, D3D11_BIND_UNORDERED_ACCESS,
            D3D11_BUFFER_DESC, D3D11_CPU_ACCESS_WRITE, D3D11_MAP_WRITE_DISCARD,
            D3D11_MAPPED_SUBRESOURCE, D3D11_SHADER_RESOURCE_VIEW_DESC,
            D3D11_SHADER_RESOURCE_VIEW_DESC_0, D3D11_TEX2D_SRV, D3D11_TEX2D_UAV,
            D3D11_TEXTURE2D_DESC, D3D11_UAV_DIMENSION_TEXTURE2D, D3D11_UNORDERED_ACCESS_VIEW_DESC,
            D3D11_UNORDERED_ACCESS_VIEW_DESC_0, D3D11_USAGE_DEFAULT, D3D11_USAGE_DYNAMIC,
            ID3D11Buffer, ID3D11ComputeShader, ID3D11DeviceContext, ID3D11ShaderResourceView,
            ID3D11Texture2D, ID3D11UnorderedAccessView,
        },
        Dxgi::Common::{
            DXGI_FORMAT, DXGI_FORMAT_D24_UNORM_S8_UINT, DXGI_FORMAT_D32_FLOAT,
            DXGI_FORMAT_D32_FLOAT_S8X24_UINT, DXGI_FORMAT_R16G16_FLOAT,
            DXGI_FORMAT_R24_UNORM_X8_TYPELESS, DXGI_FORMAT_R24G8_TYPELESS, DXGI_FORMAT_R32_FLOAT,
            DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, DXGI_FORMAT_R32_TYPELESS,
            DXGI_FORMAT_R32G8X24_TYPELESS, DXGI_SAMPLE_DESC,
        },
    },
    core::Interface,
};

/// The committed, precompiled decode compute shader (entry point `main`, `cs_5_0`).
const DECODE_DXBC: &[u8] = include_bytes!("../shaders/velocity_decode.dxbc");

/// Compute-shader thread-group size (must match `[numthreads(8, 8, 1)]` in the HLSL).
const GROUP: u32 = 8;

/// The per-dispatch inputs to the decode: the engine buffers plus the correction terms.
pub struct DecodeInputs<'a> {
    /// The engine's velocity buffer (the bias-encoded source).
    pub velocity: &'a Texture,
    /// The engine's main depth buffer, reconstructed from by the stereo reprojection correction.
    pub depth: &'a Texture,
    /// FSR's sign/axis convention, applied to the decoded UV motion.
    pub sign: (f32, f32),
    /// The stereo clip-to-previous-clip reprojection matrices (center, eye), when active.
    pub reprojection: Option<([f32; 16], [f32; 16])>,
    /// The constant camera-jitter UV offset to cancel from every vector (FSR wants jitter-free
    /// motion).
    pub jitter_uv: (f32, f32),
}

/// The decode pass: the compute shader plus the per-eye output buffer (the MV target FSR reads) and a
/// constant buffer for the size + sign convention. The velocity SRV is rebuilt per dispatch since the
/// engine's velocity texture can change underneath us.
pub struct VelocityDecode {
    shader: ID3D11ComputeShader,
    /// The R16G16F motion-vector buffer FSR consumes.
    pub output: ID3D11Texture2D,
    output_uav: ID3D11UnorderedAccessView,
    constants: ID3D11Buffer,
    width: u32,
    height: u32,
}

/// Matches the HLSL `Params` cbuffer: one register of size/sign, then the two column-major
/// reprojection matrices, then the correction flag padded to a full register.
#[repr(C)]
struct Params {
    width: u32,
    height: u32,
    sign_x: f32,
    sign_y: f32,
    reproj_center: [f32; 16],
    reproj_eye: [f32; 16],
    correction_enabled: u32,
    jitter_uv: [f32; 2],
    _padding: u32,
}

impl VelocityDecode {
    /// Build the decode pass at `width`x`height`. `None` on any D3D failure (the caller then skips
    /// motion vectors -- FSR runs with none rather than crashing).
    pub fn new(device: &Device, width: u32, height: u32) -> Option<Self> {
        let d3d = &device.m_Device;
        // SAFETY: `d3d` is the live engine device; all descriptors below are valid for these calls.
        unsafe {
            let mut shader: Option<ID3D11ComputeShader> = None;
            d3d.CreateComputeShader(DECODE_DXBC, None, Some(&mut shader))
                .ok()?;
            let shader = shader?;

            let mut output: Option<ID3D11Texture2D> = None;
            d3d.CreateTexture2D(
                &D3D11_TEXTURE2D_DESC {
                    Width: width,
                    Height: height,
                    MipLevels: 1,
                    ArraySize: 1,
                    Format: DXGI_FORMAT_R16G16_FLOAT,
                    SampleDesc: DXGI_SAMPLE_DESC {
                        Count: 1,
                        Quality: 0,
                    },
                    Usage: D3D11_USAGE_DEFAULT,
                    BindFlags: (D3D11_BIND_UNORDERED_ACCESS.0 | D3D11_BIND_SHADER_RESOURCE.0)
                        as u32,
                    CPUAccessFlags: 0,
                    MiscFlags: 0,
                },
                None,
                Some(&mut output),
            )
            .ok()?;
            let output = output?;

            let mut output_uav: Option<ID3D11UnorderedAccessView> = None;
            d3d.CreateUnorderedAccessView(
                &output,
                Some(&D3D11_UNORDERED_ACCESS_VIEW_DESC {
                    Format: DXGI_FORMAT_R16G16_FLOAT,
                    ViewDimension: D3D11_UAV_DIMENSION_TEXTURE2D,
                    Anonymous: D3D11_UNORDERED_ACCESS_VIEW_DESC_0 {
                        Texture2D: D3D11_TEX2D_UAV { MipSlice: 0 },
                    },
                }),
                Some(&mut output_uav),
            )
            .ok()?;
            let output_uav = output_uav?;

            let mut constants: Option<ID3D11Buffer> = None;
            d3d.CreateBuffer(
                &D3D11_BUFFER_DESC {
                    ByteWidth: size_of::<Params>() as u32,
                    Usage: D3D11_USAGE_DYNAMIC,
                    BindFlags: D3D11_BIND_CONSTANT_BUFFER.0 as u32,
                    CPUAccessFlags: D3D11_CPU_ACCESS_WRITE.0 as u32,
                    MiscFlags: 0,
                    StructureByteStride: 0,
                },
                None,
                Some(&mut constants),
            )
            .ok()?;
            let constants = constants?;

            Some(Self {
                shader,
                output,
                output_uav,
                constants,
                width,
                height,
            })
        }
    }

    /// Run the decode into [`Self::output`] for the buffers and correction terms in `inputs`. The
    /// caller must hold the engine context mutex (this records onto the immediate context). Returns
    /// `false` on failure.
    pub fn dispatch(
        &self,
        context: &ID3D11DeviceContext,
        device: &Device,
        inputs: &DecodeInputs<'_>,
    ) -> bool {
        let &DecodeInputs {
            velocity,
            depth,
            sign,
            reprojection,
            jitter_uv,
        } = inputs;
        // SAFETY: `device.m_Device` is live; `velocity.m_Texture` / `depth.m_Texture` are the live
        // engine buffers.
        unsafe {
            let mut velocity_srv: Option<ID3D11ShaderResourceView> = None;
            if device
                .m_Device
                .CreateShaderResourceView(
                    &velocity.m_Texture,
                    Some(&D3D11_SHADER_RESOURCE_VIEW_DESC {
                        Format: DXGI_FORMAT(velocity.m_Format as i32),
                        ViewDimension: D3D_SRV_DIMENSION_TEXTURE2D,
                        Anonymous: D3D11_SHADER_RESOURCE_VIEW_DESC_0 {
                            Texture2D: D3D11_TEX2D_SRV {
                                MostDetailedMip: 0,
                                MipLevels: 1,
                            },
                        },
                    }),
                    Some(&mut velocity_srv),
                )
                .is_err()
            {
                return false;
            }
            let velocity_srv = velocity_srv;

            // The correction needs the depth SRV; without matrices the shader never samples it, so a
            // failure to build one only downgrades the dispatch back to the uncorrected decode.
            let depth_srv = reprojection.and_then(|_| depth_srv(device, depth));
            let correction = reprojection.filter(|_| depth_srv.is_some());

            // Upload the per-dispatch params.
            let mut mapped = D3D11_MAPPED_SUBRESOURCE::default();
            if context
                .Map(
                    &self.constants,
                    0,
                    D3D11_MAP_WRITE_DISCARD,
                    0,
                    Some(&mut mapped),
                )
                .is_err()
            {
                return false;
            }
            let identity = [
                1.0, 0.0, 0.0, 0.0, //
                0.0, 1.0, 0.0, 0.0, //
                0.0, 0.0, 1.0, 0.0, //
                0.0, 0.0, 0.0, 1.0f32,
            ];
            let (reproj_center, reproj_eye) = correction.unwrap_or((identity, identity));
            let params = Params {
                width: self.width,
                height: self.height,
                sign_x: sign.0,
                sign_y: sign.1,
                reproj_center,
                reproj_eye,
                correction_enabled: u32::from(correction.is_some()),
                jitter_uv: [jitter_uv.0, jitter_uv.1],
                _padding: 0,
            };
            std::ptr::copy_nonoverlapping(&params, mapped.pData as *mut Params, 1);
            context.Unmap(&self.constants, 0);

            context.CSSetShader(&self.shader, None);
            context.CSSetShaderResources(0, Some(&[velocity_srv, depth_srv]));
            context.CSSetUnorderedAccessViews(0, 1, Some(&Some(self.output_uav.clone())), None);
            context
                .CSSetConstantBuffers(0, Some(std::slice::from_ref(&Some(self.constants.clone()))));
            context.Dispatch(self.width.div_ceil(GROUP), self.height.div_ceil(GROUP), 1);

            // Unbind the UAV / SRVs so the engine's own passes don't see them still bound.
            context.CSSetUnorderedAccessViews(0, 1, Some(&None), None);
            context.CSSetShaderResources(0, Some(&[None, None]));
            true
        }
    }
}

/// Build an SRV over the engine's depth texture. Depth resources are typeless (they carry both a DSV
/// and SRV view), so the SRV format is derived from the underlying resource description rather than
/// the engine's format field. `None` on failure (the correction is then skipped for this dispatch).
fn depth_srv(device: &Device, depth: &Texture) -> Option<ID3D11ShaderResourceView> {
    // SAFETY: `depth.m_Texture` is the live engine depth texture; the cast and desc query only read
    // it, and the created view holds its own reference.
    unsafe {
        let texture: ID3D11Texture2D = depth.m_Texture.cast().ok()?;
        let mut desc = D3D11_TEXTURE2D_DESC::default();
        texture.GetDesc(&mut desc);
        let format = match desc.Format {
            DXGI_FORMAT_R32G8X24_TYPELESS | DXGI_FORMAT_D32_FLOAT_S8X24_UINT => {
                DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS
            }
            DXGI_FORMAT_R32_TYPELESS | DXGI_FORMAT_D32_FLOAT => DXGI_FORMAT_R32_FLOAT,
            DXGI_FORMAT_R24G8_TYPELESS | DXGI_FORMAT_D24_UNORM_S8_UINT => {
                DXGI_FORMAT_R24_UNORM_X8_TYPELESS
            }
            other => other,
        };
        let mut srv: Option<ID3D11ShaderResourceView> = None;
        device
            .m_Device
            .CreateShaderResourceView(
                &depth.m_Texture,
                Some(&D3D11_SHADER_RESOURCE_VIEW_DESC {
                    Format: format,
                    ViewDimension: D3D_SRV_DIMENSION_TEXTURE2D,
                    Anonymous: D3D11_SHADER_RESOURCE_VIEW_DESC_0 {
                        Texture2D: D3D11_TEX2D_SRV {
                            MostDetailedMip: 0,
                            MipLevels: 1,
                        },
                    },
                }),
                Some(&mut srv),
            )
            .ok()?;
        srv
    }
}
